### ISSUE TITLE
Personen

### ISSUE THREAD

**Issue by MiconSchorsij** [wouterbeek/etl-andb#1]
Hoe kunnen we zowel de biografische data uit de unieke personen dataset als ook de persoonsgegevens uit de kaarten datasets, die deels overlappen, maar niet altijd identiek zijn in het linked data model onderbrengen?

**Comment by MiconSchorsij** [comment]
Eerste idee: gebruik voor de unieke personen sdo:Person en voor de persoonsgegevens andb:Person. Maar kan je dan nog wel zeggen andb:Person owl:equivalentClass sdo:Person.

**Comment by wouterbeek** [comment]
Ik zou de persoonsgegevens (= observaties over een persoon) loskoppelen van de personen zelf.

In de vorige versie werkte dit als volgt:

```
Volgens kaart A is persoon Jan Jansen geboren in 1900.
Volgens kaart B is persoon Jan Jansen geboren in 1901.
```

^ Dat zijn de persoonsgegevens / observaties.  Op basis hiervan kun je op verschillende manieren de personen aanmaken.  Hoe je dat doet is een interpretatie, liefst gebaseerd op een aantal criteria die eenvoudig zijn toe te passen.

Voorbeeld van een interpretatie, waarbij de informatie op zowel kaart A alsook kaart B correct bevonden is:

```
Persoon X heeft als naam Jan Jansen en is geboren in 1900.
Persoon Y heeft als naam Jan Jansen en is geboren in 1901.
Persoon X en persoon Y zijn niet dezelfde.
```

Voorbeeld van een andere interpretatie, waarbij de informatie op kaart B fout bevonden is:

```
Persoon X heeft als naam Jan Jansen en is geboren in 1900.
```

**Comment by wouterbeek** [comment]
Merk op dat de persoonsgegeven/observaties wel of niet correct zijn (het staat wel of niet zo op de kaart).

Maar de personen kunnen niet correct of incorrect zijn.  Hier kunnen we het alleen hebben over een 'beter' of 'slechtere' interpretatie.

**Comment by MiconSchorsij** [comment]
>  ^ Dat zijn de persoonsgegevens / observaties. Op basis hiervan kun je op verschillende manieren de personen aanmaken. 

Maar dat ga ik niet doen, ik heb personen en ik heb observaties van die personen op de kaarten. De personen modeleren heb ik feite al gedaan, lijkt me ook niet zo'n probleem om dat onder te brengen in het shape file, maar het punt is dat daar al een shape:Person in staat, die daarmee conflicteert en nu gedegradeerd moet worden tot een observatie van een persoon op een kaart. Hoe doe ik dat, daar kom ik niet uit.

Onderstaande data zou ik daarbij als voorbeeld aanvoeren:

Uit de personen graph:
`Persoon X heeft als naam Jan Jansen, is geboren in 1900 en heeft kaart 451290 en 655510.`
Uit de kaarten graph:
`Kaart 451290 ANDB lidmaatschapskaart Jan Jansen, geboren in 1900, wonend op Vrolikstraat 209, zoon van Karel Jansen, geboren in 1879.`
`Kaart 451290 ANDB lidmaatschapskaart Jan Janssen, geboren in 1901, wonend op Ruyschstraat 2-I, zoon van Karel Jansen, geboren in 1879.`

**Comment by wouterbeek** [comment]
Ik snap nog niet precies het probleem...  De shape voor persoon heeft op dit moment nog geen verwijzing naar een kaart.  Deze shape kan dus al worden toegepast voor de gecureerde set van personen die jij geprepareerd hebt.

Wanneer we naar de shape voor kaarten kijken zien we dat deze wel verwijst naar personen; dit zijn de verschillende 'about' relaties.  Deze relaties brengen kaarten in relatie met de bijbehorende personen (in jouw voorbeeld is dit, gekeerd, de "heeft kaart" frase).  Maar hierbij is het niet noodzakelijk, en ook niet wenselijk, dat deze relaties fouten die op de kaarten staan reflecteren.

Bijvoorbeeld: wanneer een kaart zegt dat persoon X geboren is in 1901 kan de 'about' relatie van die kaart naar een persoon best verwijzen naar een persoon die in 1900 geboren is.  Dit is zelfs wenselijk wanneer de kaart ten onrechte 1901 opgeeft.

De resterende vraag is nog waar de, in dit voorbeeld foutieve, waarde "1901" wordt opgeslagen.  Dit zou in een eenvoudige literal op kaart niveau kunnen.  Bijvoorbeeld `andb:claimedBirthDate "1901"^^xsd:gYear`.  In de oude versie worden hier eigenschappen genoemd o.b.v. de oorspronkelijke kolommen voor gebruikt.

**Comment by MiconSchorsij** [comment]
Er is op dit moment alleen een verwijzing van de personen naar de kaarten. De records van de kaarten hebben geen verwijzing naar de personen. Is het wenselijk dat ik dit aan de brondata ga toevoegen?

**Comment by kad-beekw** [comment]
![Untitled Diagram-Page-5 (1)](https://user-images.githubusercontent.com/62873471/100772337-bd449e80-33ff-11eb-8474-15c0eac880b5.png)


Even besproken: de meeste eigenschappen gaan over de kaart (zie link), en een beperkt aantal eigenschappen gaan over de werkelijkheid (bijv. de persoon; zie rechts).

**Comment by MiconSchorsij** [comment]
Kan je dit misschien ook in je voorbeelddata opnemen?
