### ISSUE TITLE
[CoW] Inverse relaties

### ISSUE THREAD

**Issue by MiconSchorsij** [wouterbeek/etl-andb#11]
Ik heb een voorbeeld nodig van hoe je op correcte wijze de inverse relaties in het CoW script verwerkt, zoals bijvoorbeeld hasMembership - member

**Comment by MiconSchorsij** [comment]
Volgens mij is dit eigenlijk niet zo moeilijk. De vraag is eerder: Moet je dit altijd aangeven, is het niet impliciet?

**Comment by wouterbeek** [comment]
Die inverse komt in het kennismodel te zitten.  Je hoeft hem in CoW alleen 1 richting uit toe te passen (de andere richting is dan volgens het kennismodel impliciet aanwezig).

**Comment by MiconSchorsij** [comment]
Interpreteer ik dat goed als ik concludeer dat je dan ook niet time:before EN time:after hoeft aan te geven?

**Comment by wouterbeek** [comment]
Klopt, je hoeft er maar 1 op te nemen (mag je zelf kiezen), dan vul ik de andere bij in het kennismodel.
