### ISSUE TITLE
[CoW/Druid] Integratie gegevens uit verschillende datasets

### ISSUE THREAD

**Issue by MiconSchorsij** [wouterbeek/etl-andb#8]
Data over 1 persoon is verspreid over de personen dataset en 3 kaarten datasets.

1. [https://druid.datalegend.net/MiconSchorsij/andbuniekepersonen/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fadb-andb%2F76584430-a805-4d51-b605-6f2a0875318b](https://druid.datalegend.net/MiconSchorsij/andbuniekepersonen/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fadb-andb%2F76584430-a805-4d51-b605-6f2a0875318b)

2. [https://druid.datalegend.net/MiconSchorsij/ADB/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fadb%2FAMSAB_0558_2193](https://druid.datalegend.net/MiconSchorsij/ADB/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fadb%2FAMSAB_0558_2193)

In a) staat bij de persoon aangegeven welke kaarten hij heeft en in b) staat bij de kaart aangegeven van welke persoon hij is. Als alle graphs in 1 dataset zouden zitten zou deze informatie automatisch geintegreerd worden. Zoals ook in de voorbeeld data van Wouter te zien is: 
[https://druid.datalegend.net/andb/andb2/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fdiamantbewerkers%2F7bd29f33-cfd6-4f3c-ac11-d786c255ebe3](https://druid.datalegend.net/andb/andb2/browser?resource=https%3A%2F%2Fiisg.amsterdam%2Fid%2Fdiamantbewerkers%2F7bd29f33-cfd6-4f3c-ac11-d786c255ebe3)

Of in mijn test op met personen en ADB kaarten op [https://druid.datalegend.net/MiconSchorsij/ANDBall](https://druid.datalegend.net/MiconSchorsij/ANDBall)

Maar we hebben gekozen voor losse datasets. Hoe nu toch de integratie van de data te realiseren? Of is dit geen issue?

**Comment by wouterbeek** [comment]
Fixed!

**Comment by MiconSchorsij** [comment]
1. Hoe wordt dit gefixt (ik ben geen admin, dus kan er niet achter komen)
2. de URI's https://iisg.amsterdam/id/adb/ en  https://iisg.amsterdam/id/adb-andb/ verwijzen nu wel naar mijn testomgeving,  maar de integratie van de gegevens is nog steeds niet zichtbaar
